name: Microservices CI/CD

on:
  push:
    branches: [ "lab3" ]
  pull_request:
    branches: [ "lab3" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth_service, product_service, cart_service, payment_service, notification_service, order_service]

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t microshop-app .

    - name: Run Tests inside Docker
      run: docker run --rm microshop-app pytest ${{ matrix.service }}/test_lab3.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/lab3'

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/microshop:latest
